typeb:
  - 角色
  - 事务
  - 附属
  - 秘社
  - 地区
  - 任务

colors:
  - 黄
  - 绿
  - 蓝
  - 红
  - 灰
  - 白
  - 黑
  - 紫
  - 中立

sets:
  - JC
  - XQ
  - LC
  - JZ
  - WM
  - XG
  - CQ
  - BQ

magic:
  - 心灵
  - 神圣
  - 星辰
  - 死亡
  - 鲜血
